// src/types/db.d.ts
// Placeholder for types generated by kysely-codegen

export interface DB {
  // Example:
  // person: {
  //   id: Generated<number>;
  //   first_name: string;
  //   last_name: string | null;
  //   age: number;
  // };
  // Add your table types here
}
